language: node_js
node_js:
  - 12

services:
  - docker

script:
  - docker --version #print the version for logging
  - docker build . -t user-api
  - docker tag user-api onurbolukbas/user-api

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --pasword-stdin
  - echo $FAVORITE_COUNTRY
  - echo $DOCKER_USERNAME
  - echo $DOCKER_PASSWORD
  - echo "$FAVORITE_COUNTRY"
  - docker images
  - docker push onurbolukbas/user-api
